dist: bionic
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
    - perl
    - libdbd-mysql-perl
    - build-essential
    - libxml2-dev
    - libexpat1-dev
    - libdb-dev
    - libmysqlclient-dev
    - cpanminus
      #before_install:
      #- cpanm local::lib
      #- eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
install:
  - "source ./install-travis-dependencies.sh"
script: "echo dzil test"
