dist: bionic
sudo: false
addons:
  apt:
    packages:
    - libssl-dev
    - perl
    - libdbd-mysql-perl
    - build-essential
    - libxml2-dev
    - libexpat1-dev
    - libdb-dev
    - libmysqlclient-dev
    - cpanminus
install:
  - "source ./install-travis-dependencies.sh"
script: "dzil test"
