language: perl
sudo: false
cache:
  directories:
  - perl_modules
before_install:
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
addons:
  apt:
    packages:
    - libssl-dev
perl:
  - "5.26"
install:
  - "source ./install-travis-dependencies.sh"
script: "dzil test"
